### ISSUE TITLE
in-call echo bug

### ISSUE THREAD

**Issue by enesuzun2002** [Exynos7420/android_device_samsung_zero-common#2]
When in-call other side hears their own voice.

**Comment by enesuzun2002** [comment]
https://github.com/Exynos7420/android_device_samsung_zero-common/commit/644ae69edae1464ca61804aa64f9e1337210723d

**Comment by betavr** [comment]
I have this problem when using the latest build from https://www.los-legacy.de/17.1/zeroltexx on my S6 Edge.
